// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHnjyIOuPCbYbFgZmlNIRLdxI5-ULF0E',
    appId: "1:679089501335:web:300971ccb0fb72907325d2",
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    authDomain: 'portfolio-3dacb.firebaseapp.com',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    measurementId: 'G-2C4VD948R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfxJcbMImQqHrEObReJEIUclRo2irl0qg',
    appId: '1:679089501335:android:6e5919005a0d23f87325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFkxIYxZ0-oueAhLK_iitLPoTa1ruE8C4',
    appId: '1:679089501335:ios:486b83e1dab816c57325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    androidClientId:
        '679089501335-7gibmtnlld4eib45kbtkdqn9hiqm63vb.apps.googleusercontent.com',
    iosClientId:
        '679089501335-1dmgev7gi6q8agerfjft7a7eo50j5f7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.userportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFkxIYxZ0-oueAhLK_iitLPoTa1ruE8C4',
    appId: '1:679089501335:ios:486b83e1dab816c57325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    androidClientId:
        '679089501335-7gibmtnlld4eib45kbtkdqn9hiqm63vb.apps.googleusercontent.com',
    iosClientId:
        '679089501335-1dmgev7gi6q8agerfjft7a7eo50j5f7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.userportfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQHnjyIOuPCbYbFgZmlNIRLdxI5-ULF0E',
    appId: '1:679089501335:web:300971ccb0fb72907325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    authDomain: 'portfolio-3dacb.firebaseapp.com',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    measurementId: 'G-2C4VD948R1',
  );
}
